matrix:
  include:
    - dist: bionic
      arch:
        - arm64
      os: linux
      language: python
      python:
        - "3.7.1"

      services:
        - redis-server

      # command to install dependencies
      install:
        - sudo apt-get install -y lsb-release build-essential
        - pip3 install -r requirements.txt
        - cp travis/config.yaml.template config.yaml
        - "sed -i 's|token:.*|token: '${GITHUB_TOKEN}'|g' config.yaml"
        - cat config.yaml

      script:
        # Run the test for 200 seconds.
        - python3 test_runner.py 200

    - arch:
        - arm64
      os: linux

      language: java
      jdk:
        - openjdk8

      services:
        - docker
        - redis-server

      env:
        - DOCKER_COMPOSE_VERSION=1.24.1

      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

      before_install:
        - sudo apt-get install -y libffi-dev libssl-dev
        - sudo apt-get install -y python python-pip
        - sudo apt-get remove python-configparser
        - sudo pip install docker-compose
        - sudo mkdir -p /usr/local/radar/iot
        - cd data/kotlin/docker
        - cp etc/env.template .env
        - docker-compose -f docker-compose.yml -f influxdb.yml up -d
        # Wait for services to start up.
        - sleep 50
        - cd ../data-uploader

      # command to install dependencies
      install:
        - ./gradlew build

      script:
        - screen -L -d -m -S data-uploader ./gradlew run
        - sleep 200 && screen -S data-uploader -X quit
        - cat screenlog.0